[package]
name = "HFY_Scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub-builder = "0.7.4"
rraw = "1.2.1"
tokio = { version = "1.32.0", features = ["full"] }
